package hr.prism.board.enums;

public enum Activity {

    ACCEPT_BOARD_ACTIVITY,
    ACCEPT_POST_ACTIVITY,
    CORRECT_POST_ACTIVITY,
    JOIN_DEPARTMENT_REQUEST_ACTIVITY,
    NEW_BOARD_PARENT_ACTIVITY,
    NEW_POST_PARENT_ACTIVITY,
    PUBLISH_POST_ACTIVITY,
    PUBLISH_POST_MEMBER_ACTIVITY,
    REJECT_BOARD_ACTIVITY,
    REJECT_POST_ACTIVITY,
    RESET_PASSWORD_ACTIVITY,
    RESTORE_BOARD_ACTIVITY,
    RESTORE_POST_ACTIVITY,
    RETIRE_POST_ACTIVITY,
    SUSPEND_POST_ACTIVITY

}
